# Generated by Django 2.0.5 on 2019-09-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2048)),
                ('miniatura_url', models.CharField(max_length=2048)),
                ('precio', models.FloatField()),
                ('cantidad', models.BooleanField(default=False)),
                ('libro_descripcion', models.TextField(blank=True, default=None, null=True)),
                ('upc', models.CharField(max_length=32)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='scraper.Categorias')),
            ],
        ),
    ]
