# Generated by Django 2.0.5 on 2019-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='cantidad',
            field=models.CharField(max_length=2048),
        ),
    ]
